services:
  local_db:
    container_name: work_done_local_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=work_done_local_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - local_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  local_db:
