name: Develop Branch Build

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - 'feature/**'

jobs:
  build:
    name: Build and Test Develop
    runs-on: ubuntu-latest
    environment: staging

    env:
      SPRING_PROFILES_ACTIVE: staging
      LOG_LEVEL: INFO
      DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
      DATABASE_USERNAME: ${{ secrets.STAGING_DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.STAGING_DATABASE_PASSWORD }}
      API_KEY: ${{ secrets.STAGING_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Unit Tests
        run: mvn test

      - name: Run Integration Tests
        run: mvn verify -DskipTests=false

#      - name: Publish Test Results
#        uses: EnricoMi/publish-unit-test-result-action@v2
#        if: always()
#        with:
#          files: |
#            target/surefire-reports/*.xml
#            target/failsafe-reports/*.xml

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
